JWT.xcodeproj/project.pbxproj
JWT/JWTAlgorithmFactory.m
JWT/JWTAlgorithmNone.h
JWT/JWTAlgorithmNone.m
JWTTests/JWTAlgorithmNoneSpec.m
JWTTests/JWTSpec.m

none algorithm support added
#13

None algorithm support

---

JWT.xcodeproj/project.pbxproj
JWT/JWT.h
JWT/JWT.m
JWT/JWTAlgorithmFactory.m
JWT/JWTAlgorithmNone.h
JWT/JWTAlgorithmNone.m
JWTTests/JWTAlgorithmNoneSpec.m
JWTTests/JWTSpec.m

Jwt errors

---

JWT/JWT.m
JWT/JWTAlgorithmFactory.h
JWT/JWTAlgorithmHS256.m
JWT/JWTAlgorithmHS512.m
JWT/NSData+JWT.m
JWT/NSString+JWT.m
JWTTests/JWTAlgorithmHS256Spec.m
JWTTests/JWTAlgorithmHS512Spec.m
JWTTests/JWTAlgorithmNoneSpec.m
JWTTests/JWTClaimsSerializerSpec.m
JWTTests/JWTClaimsSetSpec.m
JWTTests/JWTSpec.m
Pods/Base64/Base64/MF_Base64Additions.m

possible fixup for frameworks diamond headers

jwt: possible fix for third-party headers

---

JWT/JWT.h
JWT/JWT.m
JWTTests/JWTAlgorithmRS256Spec.m
JWTTests/JWTSpec.m

jwt: various fixes with rs256 algorithm mock and jwt error handling

---

.travis.yml

travis ci configuration updated

travis: updated

---

README.md

jwt: readme updated

---

JWT.podspec

Bump version to 1.1.1

---

README.md

code climate added
coverage added

readme: updated

---

JWT/Algorithms/JWTAlgorithm.h
JWT/Algorithms/JWTAlgorithmNone.m
JWT/JWT.h
JWT/JWT.m
JWTTests/JWTSpec.m

fluent support: added
decoding forced option: added

Fluent support

---

JWT.podspec

version: updated to 1.1.2

---

JWT.podspec

podspec: updated

---

JWT.xcodeproj/project.pbxproj
JWT.xcodeproj/xcshareddata/xcschemes/JWT.xcscheme
JWT/ClaimSet/JWTClaim.m
JWT/ClaimSet/JWTClaimsSetSerializer.m
JWT/JWT.h
JWT/JWT.m
JWTTests/JWTSpec.m
JWTTests/JWTTests-Info.plist

jwt claims verification improved
jwt fluent style tests added
project updated

Jwt verification support

---

README.md

readme: version 2.0 section added

---

JWT/Algorithms/JWTAlgorithmRS256.m

When testing my code, Apple Instrument’s showed memory leaks which came
from this file. No more leaks on these methods.
Did not check other methods in this file.

Fixed a few memory leaks

---

JWTTests/JWTSpec.m

tests: long token tests added.

---

JWT/JWT.h
JWT/JWT.m
JWTTests/JWTSpec.m

signing error added.
tests updated.

Missing signing error

---

README.md

Rs algorithms troubleshooting

---

JWT.podspec
JWT/JWT.m

- RS algorithm leaking memory fixes.
- Algorithm factory added.
- Documentation updated.
- OS X RS compatibility removed ( correct implementation needed ).

version 2.0.2

---

.gitignore
Example/JWTDesktop/JWTDesktop/JWTDesktop.xcodeproj/project.pbxproj
Example/JWTDesktop/JWTDesktop/JWTDesktop.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Example/JWTDesktop/JWTDesktop/JWTDesktop.xcworkspace/contents.xcworkspacedata
Example/JWTDesktop/JWTDesktop/JWTDesktop/AppDelegate.h
Example/JWTDesktop/JWTDesktop/JWTDesktop/AppDelegate.m
Example/JWTDesktop/JWTDesktop/JWTDesktop/Assets.xcassets/AppIcon.appiconset/Contents.json
Example/JWTDesktop/JWTDesktop/JWTDesktop/Base.lproj/Main.storyboard
Example/JWTDesktop/JWTDesktop/JWTDesktop/Info.plist
Example/JWTDesktop/JWTDesktop/JWTDesktop/ViewController.h
Example/JWTDesktop/JWTDesktop/JWTDesktop/ViewController.m
Example/JWTDesktop/JWTDesktop/JWTDesktop/main.m
Example/JWTDesktop/JWTDesktop/JWTDesktopTests/Info.plist
Example/JWTDesktop/JWTDesktop/JWTDesktopTests/JWTDesktopTests.m
Example/JWTDesktop/JWTDesktop/Podfile
Example/JWTDesktop/JWTDesktop/Podfile.lock
JWT/Algorithms/Base/JWTAlgorithmFactory.h

Example JWT Desktop app added.
It mimics jwt.io debugger behavior.
However, it needs bug fixes and further development.

Examples jwt desktop

---

JWT/Algorithms/HSFamily/JWTAlgorithmHSBase.m

As described in Issue https://github.com/yourkarma/JWT/issues/71

Free malloc memory before returning NSData

---

Example/JWTDesktop/JWTDesktop/JWTDesktop/Base.lproj/Main.storyboard
Example/JWTDesktop/JWTDesktop/JWTDesktop/ViewController.m
JWT/JWT.h
JWT/JWT.m
JWTTests/JWTSpec.m
README.md

- readme experiments section added.
- whitelists possible algorithms implementation added.
- base64urlencoding revival in decoding part.
#70 
#74

Experiments and specification compatibility improvements.

---

.gitignore
Inspection/SherlockHolmes/Podfile
Inspection/SherlockHolmes/Podfile.lock
Inspection/SherlockHolmes/SherlockHolmes.xcodeproj/project.pbxproj
Inspection/SherlockHolmes/SherlockHolmes.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Inspection/SherlockHolmes/SherlockHolmes.xcworkspace/contents.xcworkspacedata
Inspection/SherlockHolmes/SherlockHolmes/SherlockHolmes.h
Inspection/SherlockHolmes/SherlockHolmes/SherlockHolmes.m
Inspection/SherlockHolmes/SherlockHolmesTests/Info.plist
Inspection/SherlockHolmes/SherlockHolmesTests/SherlockHolmesTests.m
Inspection/SherlockHolmes/SherlockHolmesTests/SuspiciousDictionariesTests.m

Sherlock Holmes project added.

Inspection: Sherlock Holmes added.

---

.travis.yml
Classes/Algorithms/Base/JWTAlgorithmFactory.m
Classes/Algorithms/RSFamily/JWTAlgorithmRS256.h
Classes/Algorithms/RSFamily/JWTAlgorithmRS256.m
Classes/Algorithms/RSFamily/JWTAlgorithmRSBase.m
Framework/JWT.xcodeproj/project.pbxproj
Tests/JWT Tests.xcodeproj/project.pbxproj
Tests/JWT Tests.xcodeproj/xcshareddata/xcschemes/iOS_Tests.xcscheme
Tests/JWT Tests.xcodeproj/xcshareddata/xcschemes/macOS_Tests.xcscheme
Tests/Tests/Algorithms/JWTAlgorithmRS256Tests.m

- Mac OS RS compatibility added.
- Tests fixed.
- Multiplatform tests added.
- Algorithm headers deprecated.

Mac OS RS compatibility.

---

Example/JWTDesktop/JWTDesktop/Base.lproj/Main.storyboard
Example/JWTDesktop/JWTDesktop/ViewController.m

JWTDesktop updated.
Default behaviour is [JWT.IO](https://jwt.io/) now.

Example: JWTDesktop second steps.

---

Example/JWTDesktop/JWTDesktop/ViewController.m

Guard against not base64 secrets added.

Example: JWTDesktop base64 guard added.

---

.github/PULL_REQUEST_TEMPLATE.md
Classes/Algorithms/HSFamily/JWTAlgorithmHSBase.m
Classes/Algorithms/RSFamily/JWTAlgorithmRSBase.m
Classes/ClaimSet/JWTClaim.m
Classes/JWT.m
JWT.podspec

More cleanup before 2.2.0

---

.github/PULL_REQUEST_TEMPLATE.md
JWT.podspec

podspec: version updated.

---

Example/CarthageCompatibility/Cartfile.resolved
Framework/JWT.xcodeproj/project.pbxproj
Framework/Supplement/JWT-Info.plist
JWT.podspec
Tests/Podfile.lock

Carthage framework version updated.

carthage: updated. new version 2.2.0.

---

.travis.yml
Framework/JWT.xcodeproj/project.pbxproj
Framework/JWT.xcodeproj/xcshareddata/xcschemes/JWT-iOS-Static.xcscheme
Framework/JWT.xcodeproj/xcshareddata/xcschemes/JWT-iOS-Swift.xcscheme
Framework/JWT.xcodeproj/xcshareddata/xcschemes/JWT-iOS.xcscheme
Framework/JWT.xcodeproj/xcshareddata/xcschemes/JWT-macOS-Swift.xcscheme
Framework/JWT.xcodeproj/xcshareddata/xcschemes/JWT-macOS.xcscheme
Framework/JWT.xcodeproj/xcshareddata/xcschemes/JWT.xcscheme

Targets configurations updated.

---

JWT.podspec

jwt: podspec updated. version updated.

---

.gitignore
Core/Algorithms/Holders/JWTAlgorithmDataHolder.m
Inspection/SherlockHolmes/Podfile.lock
Inspection/SherlockHolmes/SherlockHolmes.xcodeproj/project.pbxproj
Tests/Tests/JWT/JWTMarkdownSpec.m
Tests/Tests/JWT/JWTSpec.m

Issues tests updated.

---

Tests/Tests.xcodeproj/project.pbxproj
Tests/Tests/JWT/JWTIssuesSpec.m
Tests/Tests/JWT/JWTSpec.m

tests: issues spec added.

---

Core/Supplement/JWTBase64Coder.m

...
Headers existence check added.

coders: headers check possible fix.

---

Core/Algorithms/RSFamily/RSKeys/JWTCryptoKey.h
Core/Algorithms/RSFamily/RSKeys/JWTCryptoKey.m
Core/Supplement/JWTBase64Coder.m
Example/JWTDesktop/JWTDesktop/JWTDecriptedViewController.h
Example/JWTDesktop/JWTDesktop/JWTDecriptedViewController.m
Example/JWTDesktop/JWTDesktop/ViewController.m

- JWTBase64Coder updated. It accepts non-base64 strings now.
- JWTDesktop example updated. RS256 is a default setup now.

RS256 is a default setup for JWTDesktop

---

Core/Algorithms/RSFamily/JWTAlgorithmRSBase.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoKey.m
Core/Coding/JWTCoding+ResultTypes.h
Core/Coding/JWTCoding+ResultTypes.m
Example/JWTDesktop/JWTDesktop.xcodeproj/project.pbxproj
Example/JWTDesktop/JWTDesktop/Base.lproj/Main.storyboard
Example/JWTDesktop/JWTDesktop/JWTTokenDecoder.h
Example/JWTDesktop/JWTDesktop/JWTTokenDecoder.m
Example/JWTDesktop/JWTDesktop/JWTTokenTextTypeDescription.h
Example/JWTDesktop/JWTDesktop/JWTTokenTextTypeDescription.m
Example/JWTDesktop/JWTDesktop/NSArrayExtension.h
Example/JWTDesktop/JWTDesktop/NSArrayExtension.m
Example/JWTDesktop/JWTDesktop/SignatureValidationDescription.h
Example/JWTDesktop/JWTDesktop/SignatureValidationDescription.m
Example/JWTDesktop/JWTDesktop/ViewController+Model.h
Example/JWTDesktop/JWTDesktop/ViewController+Model.m
Example/JWTDesktop/JWTDesktop/ViewController.m
Example/JWTDesktopSwift/JWTDesktopSwift.xcodeproj/project.pbxproj
Example/JWTDesktopSwift/JWTDesktopSwift/Array+Extension.swift
Example/JWTDesktopSwift/JWTDesktopSwift/DecriptedViewController.swift
Example/JWTDesktopSwift/JWTDesktopSwift/SignatureValidationType.swift
Example/JWTDesktopSwift/JWTDesktopSwift/String+Extension.swift
Example/JWTDesktopSwift/JWTDesktopSwift/TokenDecoder.swift
Example/JWTDesktopSwift/JWTDesktopSwift/TokenTextTypeDescription.swift
Example/JWTDesktopSwift/JWTDesktopSwift/ViewController+Model.swift
Example/JWTDesktopSwift/JWTDesktopSwift/ViewController.swift

- Memory issues have been fixed in RS family algorithms.
- Examples updated.

Memory issues have been fixed in RS family algorithms

---

JWT.podspec

Version updated.

---

Core/Coding/JWTCoding+ResultTypes.h
Core/Coding/JWTCoding+VersionThree.m
Example/JWTDesktop/JWTDesktop/JWTDecriptedCollectionViewItem.h
Example/JWTDesktop/JWTDesktop/JWTDecriptedCollectionViewItem.m
Example/JWTDesktop/JWTDesktop/JWTDecriptedViewController.m
Example/JWTDesktop/JWTDesktop/JWTTokenDecoder.m
Example/JWTDesktop/JWTDesktop/ViewController+Model.h
Example/JWTDesktop/JWTDesktop/ViewController+Model.m
Example/JWTDesktop/JWTDesktop/ViewController.m

Missing claimsSet extraction added.

---

Core/Coding/JWTCoding.h

Fixing spelling

---

Core/Algorithms/Base/JWTAlgorithmFactory.h
Core/Algorithms/Base/JWTAlgorithmFactory.m

which makes swift code a little bit better
...

Adds type for element of algorithms property of JWTAlgorithmFactory

---

Example/JWTDesktopSwift/JWTDesktopSwift/DecriptedViewController.swift
Example/JWTDesktopSwift/JWTDesktopSwift/ViewController.swift

Fixes MARK 'pragmas' in JWTDesktopSwift example

---

Example/JWTDesktopSwift/JWTDesktopSwift/TokenTextTypeDescription.swift

Gets rid of not needed casting of string to NSString

---

Example/JWTDesktopSwift/JWTDesktopSwift/ViewController.swift

Gets rid of deprecated characters String's view

---

Example/JWTDesktopSwift/JWTDesktopSwift/TokenDecoder.swift

Uses `case is` instead of `case _ as`

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
Core/Algorithms/Base/JWTAlgorithmFactory.m
Core/Algorithms/ESFamily/JWTAlgorithmESBase.m
Core/Algorithms/RSFamily/JWTAlgorithmRSBase.h
Core/Algorithms/RSFamily/JWTAlgorithmRSBase.m
Example/JWTDesktop/JWTDesktop/ViewController+Model.h
Example/JWTDesktop/JWTDesktop/ViewController+Model.m
Example/JWTDesktop/JWTDesktop/ViewController.m

Errors handling improved in RS algorithms.

Rs algorithms error handling

---

Core/Algorithms/Holders/JWTAlgorithmDataHolder.h
Core/Algorithms/Holders/JWTAlgorithmDataHolder.m
Core/Supplement/JWTBase64Coder.h
Core/Supplement/JWTBase64Coder.m
Example/JWTDesktop/JWTDesktop/ViewController+Model.h
Example/JWTDesktop/JWTDesktop/ViewController+Model.m

Possible solution for incorrect base64 coding behavior.
#181

coders: base64 coder option added. alternative behaviors for plain and base64 strings added.

---

Core/Algorithms/RSFamily/RSKeys/JWTCryptoKey.h
Core/Algorithms/RSFamily/RSKeys/JWTCryptoKey.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity.h
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity.m

- crypto security ec key extracting from ans1 added.
- crypto key raw generator added for experienced users.

Crypto key raw generator added.

---

Core/Algorithms/ESFamily/JWTAlgorithmAsymmetricBase.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoKey.h
Core/Algorithms/RSFamily/RSKeys/JWTCryptoKey.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity+ErrorHandling.h
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity+ErrorHandling.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity+ExternalRepresentation.h
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity+ExternalRepresentation.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity.h
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity.m
Core/FrameworkSupplement/JWT.h
Core/Supplement/JWTDeprecations.h
Framework/JWT.xcodeproj/project.pbxproj

- crypto security external representation has been added.
- crypto security keys types have been deprecated.

core: crypto security external representation has been added.

---

Core/Algorithms/ESFamily/JWTAlgorithmAsymmetricBase.m
Core/Algorithms/RSFamily/JWTAlgorithmRSBase.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoKey.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity.h
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity.m
Core/Coding/JWTCoding+ResultTypes.h
Core/Coding/JWTCoding+ResultTypes.m
Tests/Tests/Algorithms/JWTAlgorithmAsymmetricTests.m

- crypto security memory management has been tuned up.
- rs algorithm cleanup.
- assymetric algorithm cleanup.

core: crypto security memory management has been tuned up.

---

README.md

Chat on Gitter has been added.
Chat on Gitter platform has been added.

Chat on Gitter has been added.

---

.travis.yml
Core/Algorithms/ESFamily/JWTAlgorithmAsymmetricBase.h
Core/Algorithms/ESFamily/JWTAlgorithmAsymmetricBase.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoKey.m
Framework/JWT.xcodeproj/project.pbxproj

- PS algorithms support has been introduced.
- Project cleanup.

PS algorithms support has been introduced.

---

Core/Coding/JWTBuilder+FluentStyle.h
Core/Coding/JWTBuilder+FluentStyle.m
Core/Coding/JWTCoding+VersionTwo.h
Core/Coding/JWTCoding+VersionTwo.m
Core/FrameworkSupplement/JWT.h
Example/JWTDesktop/JWTDesktop.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Example/JWTDesktopSwift/JWTDesktopSwift.xcodeproj/project.pbxproj
Example/JWTDesktopSwift/JWTDesktopSwift.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Example/JWTDesktopSwift/JWTDesktopSwiftToolkit/TokenDecoder.swift
Example/JWTSwiftUI/JWTSwiftUI.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Example/JWTSwiftUI/JWTSwiftUI.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Example/JWTSwiftUI/JWTSwiftUI/JWTModel.swift
Framework/JWT.xcodeproj/project.pbxproj
Framework/JWT.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Tests/Tests.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

- JWTCoding version two fluent-ish blocks has been removed.

JWTCoding version two fluent-ish blocks has been removed

---

.travis.yml
Framework/JWT.xcodeproj/project.pbxproj
JWT.podspec
Tests/Tests.xcodeproj/project.pbxproj
Tests/Tests.xcodeproj/xcshareddata/xcschemes/tvOS_Tests.xcscheme
Tests/tvOS_Tests/Info.plist

Support tvOS

---

.travis.yml
Core/Algorithms/ESFamily/JWTAlgorithmAsymmetricBase.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity+ErrorHandling.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity+ExternalRepresentation.m
Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity.m
Core/FrameworkSupplement/JWT.h
Framework/JWT.xcodeproj/project.pbxproj
Framework/JWT.xcodeproj/xcshareddata/xcschemes/JWT-iOS-Static.xcscheme
Framework/JWT.xcodeproj/xcshareddata/xcschemes/JWT.xcscheme
JWT.podspec

tvOS: Warnings and missing deployment target.

---

.travis.yml
Core/Algorithms/Base/JWTAlgorithm.h
Core/Algorithms/Base/JWTAlgorithmFactory.h
Core/Algorithms/Base/JWTAlgorithmFactory.m
Core/Algorithms/Base/JWTAlgorithmNone.m
Core/Algorithms/ESFamily/JWTAlgorithmAsymmetricBase.m
Core/Algorithms/ESFamily/JWTAlgorithmESBase.m
Core/Algorithms/HSFamily/JWTAlgorithmHSBase.m
Core/Algorithms/RSFamily/JWTAlgorithmRSBase.m
Core/Coding/JWTCoding+VersionOne.m
Core/Coding/JWTCoding+VersionTwo.m
Core/Supplement/JWTBase64Coder.m
Framework/JWT.xcodeproj/project.pbxproj
JWT.podspec
Tests/Tests.xcodeproj/project.pbxproj
Tests/Tests/Algorithms/JWTAlgorithmHSTests.m
Tests/Tests/Algorithms/JWTAlgorithmNoneTests.m
Tests/watchOS_Tests/Info.plist
Tests/watchOS_Tests/watchOS_Tests.m

[Cleanup] Algorithm cleanup and watchOS.

---

.github/workflows/unit-tests.yaml
Sources/JWT/Algorithms/ESFamily/JWTAlgorithmAsymmetricBase.m
Sources/JWT/Algorithms/RSFamily/JWTAlgorithmRSBase.m
Sources/JWT/ClaimSet/JWTClaimsSetDSLBase.m
Sources/JWT/ClaimSet/JWTClaimsSetSerializerBase.m
Sources/JWT/Coding/JWTCoding+VersionOne.m
Sources/JWT/Coding/JWTCoding+VersionThree.m
Sources/JWT/Coding/JWTCoding+VersionTwo.m
Sources/JWT/include/JWT/JWTClaimsSetDSLBase.h
Sources/JWT/include/JWT/JWTClaimsSetsProtocols.h
Tests/JWTTests/Helpers/JWTAssetAccessor.m
Tests/JWTTests/Resources/Certificates.xcassets/Contents.json
Tests/JWTTests/Tests/Algorithms/JWTAlgorithmAsymmetricTests.m
Tests/JWTTests/Tests/JWT/JWTIssuesTests.m
Tests/JWTTests/Tests/JWT/JWTReadmeTests.m
Tests/JWTTests/include/JWTAssetAccessor.h

This PR fixes tests by fixing bundle lookup.
Also it fixes potential dereferences of null pointers.

Deployment. SPM. Module bundle.
